setClass("ghypbase",
         representation(lambda="numeric",
                        alpha.bar="numeric",
                        chi="numeric",
                        psi="numeric",
                        mu="numeric",
                        gamma="numeric",
                        model="character",
                        dimension="numeric",
                        expected.value="numeric"),
         prototype( lambda=1,
                    alpha.bar=1,
                    chi=1,
                    psi=1,
                    mu=0,
                    gamma=0,
                    model = "Symmetric Generalized Hyperbolic",
                    dimension=1,
                    expected.value=numeric(0))
)